// packages/vue/src/NumberFlowGroup.vue
<script lang="ts" setup>
import type { NumberFlowLite } from '@beermonster/number-flow'
import { key, type RegisterWithGroup } from './group'
import { provide, watch, type Ref, nextTick, onUnmounted } from 'vue'

const flows = new Set<Ref<NumberFlowLite | undefined>>()
let updating = false

const registerWithGroup: RegisterWithGroup = (el, parts) => {
	flows.add(el)

	watch(
		parts,
		async () => {
			if (updating) return
			updating = true
			flows.forEach(async (flow) => {
				if (!flow.value || !flow.value.created) return
				flow.value.willUpdate()
				await nextTick()
				// Optional in case the element was removed after tick:
				flow.value?.didUpdate()
			})
			await nextTick()
			updating = false
		}
		// { flush: 'pre' } // default
	)

	onUnmounted(() => {
		flows.delete(el)
	})
}

provide(key, registerWithGroup)
</script>
<template>
	<slot />
</template>

// packages/svelte/src/lib/NumberFlowGroup.svelte
<script lang="ts">
	import type { NumberFlowLite } from '@beermonster/number-flow'
	import { type Readable, get } from 'svelte/store'
	import { beforeUpdate, onDestroy, tick } from 'svelte'
	import { type RegisterWithGroup, setGroupContext } from './group.js'

	const flows = new Set<Readable<NumberFlowLite | undefined>>()
	let updating = false

	const registerWithGroup: RegisterWithGroup = (el) => {
		flows.add(el)

		beforeUpdate(async () => {
			if (updating) return
			updating = true
			flows.forEach(async (flow) => {
				{
					const f = get(flow)
					if (!f || !f.created) return
					f.willUpdate()
				}
				await tick()
				// Optional in case the element was removed after tick:
				get(flow)?.didUpdate()
			})
			await tick()
			updating = false
		})

		onDestroy(() => {
			flows.delete(el)
		})
	}

	setGroupContext({ register: registerWithGroup })
</script>

<slot />
